import '@scripts/admin/animation';
import '@scripts/admin/button-icon-color';
import '@scripts/admin/responsive-panel';
import '@scripts/admin/masked-image-width';
import '@scripts/admin/blocks/slider-editor';
import '@scripts/admin/blocks/slide-editor';
import '@scripts/admin/blocks/tabs-editor';
import '@scripts/admin/blocks/tab-editor';
import '@scripts/admin/paragraph';
import '@scripts/admin/columns';
import '@scripts/admin/group';
import '@scripts/admin/heading';
import '@scripts/admin/buttons';
import '@scripts/admin/accordion';
import '@scripts/admin/list';
import '@scripts/admin/cover';
import '@scripts/admin/table';
import '@scripts/admin/font-styles';

